In [1]:
import pandas as pd

In [ ]:
notes = pd.Series(
    [12, 15, 18, 14],
    index=["Ali", "Sara", "Omar", "Lina"]
)
print(notes)
#récupérer une valeur
print(notes["Sara"])

Ali     12
Sara    15
Omar    18
Lina    14
dtype: int64
15

In [5]:
#DataFrame
data = {
    "Nom": ["Ali", "Sara", "Omar", "Lina"],
    "Age": [25, 30, 28, 35],
    "Salaire": [4000, 5500, 4800, 6500]
}

df = pd.DataFrame(data)

print(df)
print(df.shape)

    Nom  Age  Salaire
0   Ali   25     4000
1  Sara   30     5500
2  Omar   28     4800
3  Lina   35     6500
(4, 3)

In [6]:
# Selectionner plusieurs colonnes:
print(df[["Nom", "Salaire"]])

    Nom  Salaire
0   Ali     4000
1  Sara     5500
2  Omar     4800
3  Lina     6500

In [ ]:
#exerice heure 1 J6
data = {
    "Produit": ["PC", "Téléphone", "Tablette", "Écran", "Clavier"],
    "Prix": [8000, 4500, 3200, 2000, 500],
    "Stock": [5, 12, 8, 15, 30]
}
#1
df = pd.DataFrame(data)
#2
print(df)
#3
print(df.shape)
#4
print(df.columns)
#5
print(df["Prix"])
#6
print(df[["Produit","Stock"]])
#7
#c'est une serie car df["Prix"] a 1D
#8
#c'est une DataFrame car df[["Prix"]] a 2D

     Produit  Prix  Stock
0         PC  8000      5
1  Téléphone  4500     12
2   Tablette  3200      8
3      Écran  2000     15
4    Clavier   500     30
(5, 3)
Index(['Produit', 'Prix', 'Stock'], dtype='str')
   Prix
0  8000
1  4500
2  3200
3  2000
4   500
     Produit  Stock
0         PC      5
1  Téléphone     12
2   Tablette      8
3      Écran     15
4    Clavier     30

In [ ]:
df = pd.read_csv("produits.csv")
#1 #2
print(df)
#3
print(df.shape)
#4
print(df.columns)
#5
print(df["Stock"])
#6
print(df[["Produit","Prix"]])
#7
# la DataFrame aura 5 lignes et 3 colonnes car dans le CSV la premiere lignes a trois colonnes et au dessous il y a 5 lignes

     Produit  Prix  Stock
0         PC  8000      5
1  Telephone  4500     12
2   Tablette  3200      8
3      Ecran  2000     15
4    Clavier   500     30
(5, 3)
Index(['Produit', 'Prix', 'Stock'], dtype='str')
0     5
1    12
2     8
3    15
4    30
Name: Stock, dtype: int64
     Produit  Prix
0         PC  8000
1  Telephone  4500
2   Tablette  3200
3      Ecran  2000
4    Clavier   500

Quand On reçoit un nouveau CSV, un bon premier réflexe est :
Ce petit bloc te donne déjà une excellente première compréhension du dataset.
En Data Analysis, on appelle cette étape l’exploration initiale des données.

In [ ]:
df = pd.read_csv("fichier.csv")

print(df.head())
print(df.shape)
print(df.columns)
print(df.dtypes)

df.info()

print(df.describe())

In [33]:
#Jour 7 : Selection et filtres 
data = {
    "Nom": ["Ali", "Sara", "Omar", "Lina", "Youssef"],
    "Age": [25, 30, 28, 35, 40],
    "Ville": ["Casa", "Rabat", "Casa", "Marrakech", "Rabat"],
    "Salaire": [4000, 5500, 4800, 6500, 7200]
}

df = pd.DataFrame(data)
df
df.index = ["E101", "E102", "E103", "E104", "E105"]
#1
df.loc["E103","Salaire"]
#2
df.loc["E105"]
#3
df.loc["E102":"E104"]
#4
df.loc["E102":"E104",["Nom","Salaire"]]
#5
df.iloc[2]
#6
df.iloc[4,1]
#7
#parceque .loc utilse labelle pour les lignes , puisque on a changer l'index donc 2 n'existe plus
#8
#parceque .iloc ne regarde pas sur les noms , elle donne les positions numrqiues des lignes comme des colonnes

np.int64(40)

In [ ]:
data = {
    "Client": ["Ali", "Sara", "Omar", "Lina", "Youssef", "Salma", "Amine", "Nadia"],
    "Ville": ["Casa", "Rabat", "Casa", "Marrakech", "Rabat", "Casa", "Tanger", "Marrakech"],
    "Produit": ["PC", "Telephone", "Tablette", "PC", "Ecran", "Telephone", "PC", "Tablette"],
    "Categorie": ["Informatique", "Mobile", "Mobile", "Informatique",
                  "Informatique", "Mobile", "Informatique", "Mobile"],
    "Montant": [8000, 4500, 3200, 9000, 2500, 5000, 7500, 3800],
    "Quantite": [1, 2, 1, 1, 2, 3, 1, 2]
}

df = pd.DataFrame(data)
df
#1
df.loc[:,["Client","Produit","Montant"]]
#2
df.loc[2:5,]
#3
df.iloc[0:4,0:3]
#4
df[df["Montant"] > 5000]
#5
df[df["Ville"].isin(["Casa","Rabat"])]
#6
df[(df["Categorie"] == "Informatique") & (df["Montant"] >= 7000)]
#7
df[df["Montant"].between(3500,6000)]
#8
df.loc[df["Quantite"] >= 2 ,["Client","Ville","Montant"]]
#9
df[df["Produit"].isin(["PC","Telephone","Ecran"])]
#10
df[(df["Ville"] == "Casa") & (df["Quantite"] > 1)]
#11
df[(df["Ville"] == "Marrakech") | (df["Montant"] > 7000)]
#12
df.iloc[5,3]
#13
df[(df["Ville"]=="Rabat") & (df["Montant"] > 3000)]
#14
df.loc[(df["Ville"].isin(["Casa","Marrakech"])) & (df["Montant"].between(3000,8000)),["Client","Produit","Montant"]]
#15
#.loc prendre les lignes et les colonnes dous forme de labels et noms par contre .iloc le prendre sous forme de position numerique

  Client    Produit  Montant
0    Ali         PC     8000
2   Omar   Tablette     3200
5  Salma  Telephone     5000
7  Nadia   Tablette     3800

J-8	Colonnes & types

In [ ]:
#Exercice 2:
data = {
    "Produit": ["PC", "Telephone", "Tablette", "Ecran", "Clavier"],
    "Prix": [8000, 4500, 3200, 2000, 500],
    "Quantite": [2, 3, 4, 5, 10]
}
df = pd.DataFrame(data)
df
#1
df["Prix"] = df["Prix"] * 1.1
df
#2
df["Total"] = df["Prix"] * df["Quantite"]
#3
df["Devise"] = "MAD"
#4
df = df.rename(columns={"Prix" : "Prix_Unitaire"})
#5
df = df.rename(columns={"Quantite" : "Qte"})
#6
df = df.drop(columns = ["Devise"])
#7
df

     Produit  Prix_Unitaire  Qte    Total
0         PC         8800.0    2  17600.0
1  Telephone         4950.0    3  14850.0
2   Tablette         3520.0    4  14080.0
3      Ecran         2200.0    5  11000.0
4    Clavier          550.0   10   5500.0

In [ ]:
#exercice 1:
data = {
    "Produit": ["PC", "Telephone", "Tablette", "Ecran", "Clavier"],
    "Prix": ["8000", "4500", "3200", "2000", "500"],
    "Quantite": ["2", "3", "4", "5", "10"],
    "Disponible": [True, True, False, True, False]
}

df = pd.DataFrame(data)
df
#1
df.dtypes
#2
df["Prix"]=df["Prix"].astype(float)
#3
df["Quantite"]=df["Quantite"].astype(int)
#4
df.dtypes
#5
df["Total"] = df["Prix"] * df["Quantite"]
#6
df["Produit"]=df["Produit"].astype(str)
#7
df["Total"]=df["Total"].astype(int)
#8
df
df.dtypes
#9
#les entiers somt entres " " donc python le lire comme des str pas des int 10 != "10"
#10
#le code va echouer , car on ne peut pas transformer un str en int

Produit           str
Prix          float64
Quantite        int64
Disponible       bool
Total           int64
dtype: object

Jour 9 : Nettoyage : valeurs manquantes

In [ ]:
#Exercice 1 :
import pandas as pd
import numpy as np

data = {
    "Nom": ["Ali", "Sara", "Omar", "Lina", "Youssef", "Salma"],
    "Age": [25, 30, np.nan, 35, 40, 28],
    "Ville": ["Casa", "Rabat", "Casa", None, "Rabat", "Casa"],
    "Salaire": [4000, 5500, 4800, 6500, np.nan, np.nan]
}

df = pd.DataFrame(data)
#1
df
#2
df.isna().sum()
#3
df.isna().sum().sum()
#4
df[df["Age"].isna()]
#5
df[df["Salaire"].isna()]
#6
df[df["Salaire"].notna()]
#7
df.loc[df["Salaire"].isna(),["Nom","Salaire"]]
#8
df.info()
# Ville    5 non-null
#9
#isna() cherche les valeurs manquantes et lui donne True , notna() cherche les valeurs presentes et lui donne True
#10
# la somme des valeurs manquantes dans chaque colonne

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nom      6 non-null      str
 1   Age      5 non-null      float64
 2   Ville    5 non-null      str
 3   Salaire  4 non-null      float64
dtypes: float64(2), str(2)
memory usage: 324.0 bytes

La moyenne est :

(4000 + 5500 + 4800 + 6500) / 4
= 5200

On peut donc remplacer les salaires manquants par la moyenne :

df["Salaire"] = df["Salaire"].fillna(
    df["Salaire"].mean())

In [ ]:
data = {
    "Nom": ["Ali", "Sara", "Omar", "Lina", "Youssef", "Salma"],
    "Age": [25, 30, np.nan, 35, 40, 28],
    "Ville": ["Casa", "Rabat", "Casa", None, "Rabat", "Casa"],
    "Salaire": [4000, 5500, 4800, 6500, np.nan, np.nan]
}

df = pd.DataFrame(data)
#1
df["Salaire"].mean()
#2
df["Age"].median()
#3
df["Ville"].mode()[0]
#4
df["Age"]=df["Age"].fillna(df["Age"].median())
#5
df["Ville"] = df["Ville"].fillna(df["Ville"].mode()[0])
#6
df["Salaire"] = df["Salaire"].fillna(df["Salaire"].mean())
#7
df.isna().sum()
#8
df
#9
#car ville est str on ne peut pas faire la moyenne c'est absurde. Donc on doit utiliser le mode
#10
#Quand on aura une valeur tres grande ou tres petite en comparant avec les autres valeurs , donc ici la mediane est la meilleur chemin

       Nom   Age  Ville  Salaire
0      Ali  25.0   Casa   4000.0
1     Sara  30.0  Rabat   5500.0
2     Omar  30.0   Casa   4800.0
3     Lina  35.0   Casa   6500.0
4  Youssef  40.0  Rabat   5200.0
5    Salma  28.0   Casa   5200.0

J10- Nettoyage : doublons & texte

In [ ]:
#Exercice 1 :
data = {
    "Code_Client": ["C01", "C02", "C03", "C02", "C04", "C05", "C03", "C06"],
    "Nom": ["Ali", "Sara", "Omar", "Sara", "Lina", "Youssef", "Omar", "Nadia"],
    "Ville": ["Casa", "Rabat", "Casa", "Rabat", "Marrakech", "Rabat", "Casa", "Casa"],
    "Montant": [4500, 6000, 5200, 6000, 7000, 6500, 5200, 4800]
}

df = pd.DataFrame(data)
#1
df
#2
df.duplicated()
#3
df[df.duplicated()]
#4
df.duplicated().sum()
#5
df[df.duplicated(keep = False)]
#6
df.duplicated(subset = ["Code_Client"])
#7
df = df.drop_duplicates(keep = "first")
#8
df = pd.DataFrame(data)
df = df.drop_duplicates(subset=["Code_Client"],keep="last")
#9
df.duplicated().sum()
#10
""" df.duplicated() detecte les doublons des lignes dans n'importe quel colonnes seulement si les 
doublons sont complets . df.duplicated(subset=["Code_Client"]) detecte les doublons uniquement dans la
colonne Code_Client """
df=pd.DataFrame(data)

  Code_Client   Nom  Ville  Montant
1         C02  Sara  Rabat     6000
2         C03  Omar   Casa     5200
3         C02  Sara  Rabat     6000
6         C03  Omar   Casa     5200

In [ ]:
#Exercice 2 :
data = {
    "Client": ["  ali", "SARA ", " omar ", "LINA", " youssef "],
    "Ville": ["CASA ", " rabat", "Casa", " MARRAKECH ", "RABAT"],
    "Email": [
        " ALI@GMAIL.COM ",
        "SARA@YAHOO.COM",
        " omar@gmail.com",
        "LINA@GMAIL.COM ",
        " YOUSSEF@YAHOO.COM "
    ]
}
df = pd.DataFrame(data)
#1
df["Client"]=df["Client"].str.strip()
#2
df["Client"]=df["Client"].str.lower().str.title()
#3
df["Ville"]=df["Ville"].str.strip()
#4
df["Ville"]=df["Ville"].str.lower().str.title()
#5
df["Email"]=df["Email"].str.strip()
#6
df["Email"]=df["Email"].str.lower()
#7
df[df["Email"].str.contains("gmail")]
#8
df["Client"].str.len()
#9
df["Ville"]=df["Ville"].str.replace("Casa","Casablanca")
#10
df

0    3
1    4
2    4
3    4
4    7
Name: Client, dtype: int64

J-11	Dates et heures

In [ ]:
#Exercice 1:
data = {
    "Commande": ["CMD01", "CMD02", "CMD03", "CMD04", "CMD05"],
    "Date": [
        "01/09/2026",
        "03/09/2026",
        "05/09/2026",
        "08/09/2026",
        "10/09/2026"
    ],
    "Montant": [4500, 6200, 5100, 7000, 5800]
}
df = pd.DataFrame(data)
#1
df
#2
df.dtypes
#3
df["Date"]=pd.to_datetime(df["Date"],format="%d/%m/%Y")
#4
df.dtypes
#5
#Date        datetime64[us]
#6
#car python pandas donne a chaque texte ou nombre entre "" donne le le format du object , str.
#7
#d/m/Y
#8
#Y-m-d
#9
#errors="coerce" sert a remplacer une date inconnue avec Nat 
#10
#Nat , not a time

Commande               str
Date        datetime64[us]
Montant              int64
dtype: object

In [ ]:
#Exercice 2:
data = {
    "Commande": ["CMD01", "CMD02", "CMD03", "CMD04", "CMD05", "CMD06"],
    "Date_Commande": [
        "01/08/2026",
        "15/08/2026",
        "03/09/2026",
        "10/09/2026",
        "20/09/2026",
        "05/10/2026"
    ],
    "Date_Livraison": [
        "04/08/2026",
        "18/08/2026",
        "08/09/2026",
        "12/09/2026",
        "27/09/2026",
        "09/10/2026"
    ],
    "Montant": [4000, 5500, 6200, 7000, 4800, 8000]
}

df = pd.DataFrame(data)
#1
df["Date_Commande"] = pd.to_datetime(df["Date_Commande"],format="%d/%m/%Y")
df["Date_Livraison"]= pd.to_datetime(df["Date_Livraison"],format="%d/%m/%Y")
df.dtypes
#2
df["Annee"] = df["Date_Commande"].dt.year
df["Annee"]
#3
df["mois"]= df["Date_Commande"].dt.month
df["mois"]
#4
df["Jour"] = df["Date_Commande"].dt.day
df["Jour"]
#5
df["Jour_Semaine"] = df["Date_Commande"].dt.day_name()
df["Jour_Semaine"]
#6
df[ df["mois"] == 9 ]
#7
df[df["Date_Commande"] >= "2026-09-10"]
#8
df[df["Date_Commande"].between("2026-09-03","2026-09-20")]
#9
df["Duree_Jours"] = (
    df["Date_Livraison"] - df["Date_Commande"]
).dt.days
#10
df[df["Duree_Jours"] > 4]
#11
df["Date_Commande"].min()
#12
df["Date_Commande"].max()
#13
# Timedelta représente une durée / différence entre deux dates
#14
#car parfois on peut observer que la date est un objet , donc un objet avec dt.year c'est une erreur

  Date_Commande
5    2026-10-05

0    False
1    False
2     True
3     True
4     True
5    False
6    False
Name: Date_Commande, dtype: bool

J12-	GroupBy & agrégations

In [ ]:
#Exercice 1:
import pandas as pd

data = {
    "Vendeur": ["Ali", "Sara", "Ali", "Omar", "Sara", "Ali", "Omar", "Sara"],
    "Ville": ["Casa", "Rabat", "Casa", "Casa", "Rabat", "Rabat", "Casa", "Casa"],
    "Produit": ["PC", "Telephone", "Ecran", "PC", "PC", "Telephone", "Ecran", "PC"],
    "Montant": [8000, 4500, 2000, 7500, 8200, 5000, 2200, 7800],
    "Quantite": [1, 2, 2, 1, 1, 3, 2, 1]
}

df = pd.DataFrame(data)
#1
df.groupby("Vendeur")["Montant"].sum()
#2
df.groupby("Vendeur")["Montant"].mean().round(2)
#3
df.groupby("Vendeur")["Quantite"].sum()
#4
df.groupby("Vendeur")["Montant"].max()
#5
df.groupby("Vendeur")["Montant"].min()
#6
df.groupby("Vendeur")["Montant"].count()
#7
df.groupby("Vendeur")["Montant"].size()
#8
df.groupby("Ville")["Montant"].sum()
#9
df.groupby("Ville")["Montant"].mean()
#10
df.groupby("Produit")["Quantite"].sum()
#11
df.groupby("Vendeur")["Montant"].sum().reset_index()
#12
""" df["Montant"].sum() retourne la somme du montant de tous les vendeur en une seule ligne  
df.groupby("Vendeur")["Montant"].sum() retourne la somme du montant de chaque vendeur en des groupes """

Vendeur
Ali     3
Omar    2
Sara    3
Name: Montant, dtype: int64

In [ ]:
#Exercice 2:
data = {
    "Vendeur": ["Ali", "Sara", "Ali", "Omar", "Sara", "Ali", "Omar", "Sara"],
    "Ville": ["Casa", "Rabat", "Casa", "Casa", "Rabat", "Rabat", "Casa", "Casa"],
    "Produit": ["PC", "Telephone", "Ecran", "PC", "PC", "Telephone", "Ecran", "PC"],
    "Montant": [8000, 4500, 2000, 7500, 8200, 5000, 2200, 7800],
    "Quantite": [1, 2, 2, 1, 1, 3, 2, 1]
}

df = pd.DataFrame(data)
#1
df.groupby(["Vendeur","Ville"]).agg(montant_total = ("Montant","sum"))
#2
df.groupby(["Vendeur","Ville"]).agg(montant_total = ("Montant","sum")).reset_index()
#3
df.groupby("Vendeur")["Montant"].agg(["sum","mean","min","max"]).reset_index()
#4
df.groupby("Vendeur").agg({"Montant" : ["sum"],"Quantite":["sum"]}).reset_index()
#5
df.groupby("Ville").agg({"Montant" :["sum","mean"],"Quantite" : ["sum"]}).reset_index()
#6
df.groupby(["Ville", "Produit"]).agg(
    Montant_Total=("Montant", "sum")
).reset_index()
#7
df.groupby("Vendeur").agg(
 CA_Total = ("Montant","sum"),
 Vente_Moyenne =("Montant","mean"),
 Quantite_Total = ("Quantite","sum")).reset_index()
#8
df.groupby("Vendeur").agg(
 CA_Total = ("Montant","sum"),
 Vente_Moyenne =("Montant","mean"),
 Quantite_Totale = ("Quantite","sum"),
 Nb_Ventes = ("Montant","count")).reset_index()
#9
df.groupby("Ville").agg(
 CA_Total = ("Montant","sum"),
 Vente_Min =("Montant","min"),
 Vente_Max = ("Montant","max"),
 Quantite_Totale = ("Quantite","sum")).reset_index()
#10
''' groupby("Vendeur") grouper par une seule colonne Vendeur
groupby(["Vendeur", "Ville"]) grouper par deux colonnes Vendeur et Ville '''
#11
#.agg() permet d'appliquer plusieurs fonctions d'agrégation en une seule opération, éventuellement sur plusieurs colonnes.
#12
''' CA_Total est un alias de nouveau colonne
Montant est une colonne
sum operation '''

   Ville  CA_Total  Vente_Min  Vente_Max  Quantite_Totale
0   Casa     27500       2000       8000                7
1  Rabat     17700       4500       8200                6

  Vendeur    Produit  CA_Totale
0     Ali      Ecran       2200
1     Ali         PC      16500
2     Ali  Telephone       5200
3    Omar      Ecran       5500
4    Omar  Telephone       4800
5    Sara         PC      16000
6    Sara  Telephone       4500

J13	Merge / Join / Concat

In [ ]:
#Exercice 1:
clients = pd.DataFrame({
    "Client_ID": [1, 2, 3, 4],
    "Nom": ["Ali", "Sara", "Omar", "Lina"],
    "Ville": ["Casa", "Rabat", "Casa", "Marrakech"]
})

commandes = pd.DataFrame({
    "Commande_ID": ["CMD01", "CMD02", "CMD03", "CMD04"],
    "Client_ID": [1, 2, 2, 5],
    "Montant": [4500, 6200, 3000, 7000]
})
#1
df_merge = pd.merge(clients,commandes,on ="Client_ID",
    how = "inner")
df_merge.shape
#2
df_merge = pd.merge(clients,commandes,on ="Client_ID",
    how = "left")
df_merge.shape
#3
df_merge = pd.merge(clients,commandes,on ="Client_ID",
    how = "right")
df_merge.shape
#4
df_merge = pd.merge(clients,commandes,on ="Client_ID",
    how = "outer")
df_merge.shape
#5
# voir les questions 1 2 3 et 4
#6
# left et outer join
#7
# right et outer join
#8
# car elle a deux commandes CMD02 et CMD03
#9
""" inner garde uniquement les lignes dont la clé existe dans les deux DataFrames.
left garde toutes les lignes du DataFrame de gauche, même lorsqu'il n'existe aucune correspondance à droite. """
#10
""" left  → garde toutes les clés du DataFrame de gauche
outer → garde toutes les clés présentes dans l'un OU l'autre DataFrame """
#11
df_merge = pd.merge(clients,commandes,on ="Client_ID",
    how = "left")
#12
df_merge.isna().sum()

   Client_ID   Nom      Ville Commande_ID  Montant
0          1   Ali       Casa       CMD01   4500.0
1          2  Sara      Rabat       CMD02   6200.0
2          2  Sara      Rabat       CMD03   3000.0
3          3  Omar       Casa         NaN      NaN
4          4  Lina  Marrakech         NaN      NaN
5          5   NaN        NaN       CMD04   7000.0

In [ ]:
#Exercice 2:
clients = pd.DataFrame({
    "Client_ID": [1, 2, 3, 4],
    "Nom": ["Ali", "Sara", "Omar", "Lina"],
    "Ville": ["Casa", "Rabat", "Casa", "Marrakech"]
})

commandes = pd.DataFrame({
    "Commande_ID": ["CMD01", "CMD02", "CMD03", "CMD04"],
    "Code_Client": [1, 2, 2, 5],
    "Montant": [4500, 6200, 3000, 7000]
})

ventes = pd.DataFrame({
    "Vendeur": ["Ali", "Ali", "Sara", "Sara"],
    "Ville": ["Casa", "Rabat", "Casa", "Rabat"],
    "Montant": [8000, 5000, 7800, 4500]
})

objectifs = pd.DataFrame({
    "Vendeur": ["Ali", "Ali", "Sara", "Sara"],
    "Ville": ["Casa", "Rabat", "Casa", "Rabat"],
    "Objectif": [9000, 6000, 7500, 5000]
})

#1
df_merge = pd.merge(clients,commandes,left_on = "Client_ID",right_on="Code_Client",how="inner")
#2
df_merge = pd.merge(clients,commandes,left_on = "Client_ID",right_on="Code_Client",how="left")
#3
df_merge = pd.merge(clients,commandes,left_on = "Client_ID",right_on="Code_Client",how="outer")
#4
df_merge= pd.merge(ventes,objectifs,on=["Vendeur","Ville"],how="inner")
#5
df_merge= pd.merge(ventes,objectifs,on=["Vendeur","Ville"],how="left")
#6
# car il nous cause un probleme , deux cles ou plus permet de preciser efficacement quel vendeur .
#7
clients_index = clients.set_index("Client_ID")
#set_index transforme le Client_ID en index , car il a ete  une colonne avant
#8
infos = pd.DataFrame({
    "Categorie": ["Premium", "Standard", "Premium"]
}, index=[1, 2, 4])
df_join = clients_index.join(infos,how="left")
#9
df_join = clients_index.join(infos,how="inner")
#10
""" merge() tres pratique avec les colonnes
join() tres pratique avec les index """ 
#11
# left_on et right_on pour combiner les cles differentes des dataFrames
#12
#on=["Vendeur", "Ville"] : condition de jointure en deux cles Vendeur et Ville
#13
# suffixes  sert a separer les memes colonnes , en donnant colonnes_x et colonnes_y
#14
""" clients.join(infos, on="Client_ID") : ici clients est colonnes et infos index
et on veut combiner les deux dataFrames
clients_index.join(infos) clients et infos sont deux index """

            Nom      Ville Categorie
Client_ID
1           Ali       Casa   Premium
2          Sara      Rabat  Standard
3          Omar       Casa       NaN
4          Lina  Marrakech   Premium

In [ ]:
#Exercice de Synthese :
clients = pd.DataFrame({
    "Client_ID": [1, 2, 3, 4],
    "Nom": ["Ali", "Sara", "Omar", "Lina"],
    "Ville": ["Casa", "Rabat", "Casa", "Marrakech"]
})

commandes_aout = pd.DataFrame({
    "Commande_ID": ["A01", "A02", "A03"],
    "Client_ID": [1, 2, 3],
    "Montant": [4500, 6200, 5100]
})

commandes_septembre = pd.DataFrame({
    "Commande_ID": ["S01", "S02", "S03", "S04"],
    "Client_ID": [1, 2, 2, 5],
    "Montant": [5000, 6500, 3200, 7000]
})

categories = pd.DataFrame({
    "Categorie": ["Premium", "Standard", "Premium", "Standard"]
}, index=[1, 2, 3, 4])

#1
commandes = pd.concat([commandes_aout,commandes_septembre],axis=0,ignore_index=True)
#2
commandes.shape
#3
df_merge = pd.merge(clients,commandes,on="Client_ID",how="inner")
#4
df_merge = pd.merge(clients,commandes,on="Client_ID",how="left")
#5
df_merge = pd.merge(clients,commandes,on="Client_ID",how="outer")
#6
""" car client_ID = 2 il est present dans commandes_septembre deux fois et clients 
donc il la plupart de la chance pour apparaitre dans right ou inner ou outer ou left """
#7
# car il est present seulement dans commandes_septembre et il est absent dans aout et clients
#8
clients_index = clients.set_index("Client_ID")
#9
df_join = clients_index.join(categories,how="left")
#10
df_join.isna().sum()
#11
eleves = pd.DataFrame({"Eleve" : ["tres bien","Mediocre","Passable"]},index=[1,2,3])
books = pd.DataFrame({"Book" : ["Dernier Jour","Prince","GOT"]},index=[1,2,3])
pd.concat([eleves,books],axis=1)
#12
""" axis=0 : verticale , ajoute les lignes
 axis=1 horizontale , ajoute les colonnes """
#13
#ignore_index=True permet de continuer le compte sans retourne a 0
#14-15
""" Utilise concat() lorsque tu veux surtout empiler ou juxtaposer des DataFrames, 
sans rechercher une correspondance via une clé."""
#16
# merge : les colonnes
# join : les index
#17
# alignement automatique des index par pandas
#18
#Pandas applique également un alignement automatique, mais cette fois sur les noms de colonnes
#19
# pour verifier que l'operation a ete effectuer bien et fixer les defauts , sinon il sera comme une tour avec une base friable
#20
""" merge()
→ relie des DataFrames en faisant correspondre une ou plusieurs clés.
join()
→ relie des DataFrames, particulièrement facilement à partir de leurs index.
concat()
→ assemble des DataFrames verticalement (axis=0) ou horizontalement (axis=1),
  sans faire une jointure sur une clé métier. """

           0             1
1  tres bien  Dernier Jour
2   Mediocre        Prince
3   Passable           GOT

J14	 Pivot

In [ ]:
#Exercice:
import pandas as pd

data = {
    "Vendeur": ["Ali", "Sara", "Ali", "Omar", "Sara", "Ali", "Omar", "Sara"],
    "Ville": ["Casa", "Rabat", "Casa", "Casa", "Rabat", "Rabat", "Casa", "Casa"],
    "Produit": ["PC", "Telephone", "Ecran", "PC", "PC", "Telephone", "Ecran", "PC"],
    "Montant": [8000, 4500, 2000, 7500, 8200, 5000, 2200, 7800],
    "Quantite": [1, 2, 2, 1, 1, 3, 2, 1]
}
df = pd.DataFrame(data)
#1
pd.crosstab(df["Ville"],df["Produit"],values=df["Montant"],aggfunc="sum",margins = True)
#2
pd.crosstab(df["Ville"],df["Produit"],values=df["Montant"],aggfunc="sum",margins = True).fillna(0)
#3
pd.crosstab(df["Ville"],df["Produit"],values=df["Montant"],aggfunc="mean",margins = True).fillna(0)
#4
pd.pivot_table(df,values = "Quantite",index = "Vendeur",columns = "Produit",aggfunc = "sum")
#5
pd.pivot_table(df,values = "Montant",index = ["Ville","Vendeur"],columns = "Produit",aggfunc = "sum")
#6
pd.pivot_table(df,values = "Montant",index = "Ville",columns = "Produit",aggfunc = ["sum","mean"])
#7
pd.pivot_table(df,values = "Montant",index = "Ville",columns = "Produit",aggfunc = "sum",fill_value = 0,margins=True)
#8
pd.crosstab(df["Ville"],df["Produit"])
#9
pd.crosstab(df["Ville"],df["Produit"],margins=True)
#10
"""groupby : Somme et moyenne par groupes
pivot_table : Tableau de synthèse lignes * colonnes"""
#11
""" pivot_table : Tableau de synthèse lignes * colonnes
crosstab : Compter les combinaisons de catégories"""
#12
"""values : la valeur qu'on va la calculer 
 index: les lignes
columns: les colonnes 
aggfunc : operation mathematique : sum ou mean ou min ou max ..."""

Produit  Ecran  PC  Telephone  All
Ville
Casa         2   3          0    5
Rabat        0   1          2    3
All          2   4          2    8